### PR TITLE
Expanded SystemStateDispatcher

### PR DESCRIPTION
**Pull request by RonnyWinkler**
Hello Harrie,

finally here are the low hanging fruits :-)

- Changed delay from 30 to 60 seconds. Minimum state change is 1min for systemload, so it's a sensible compromise.
- Added topic folder system/systemload with values for 1, 5 and 15 minute interval
- Added topic folder /system/memusage with values for applist, free, used, total memory
- still used one timeout (60sec). Internal a counter is used to update the 5 and 15 min interval elements.

Example of MQTT topic:
grafik

Example of app list ordered descending by memory usage:
grafik

Please check if this implementation is ok for you. It's a bit low level using a counter variable but I wanted to prevent usage of more timeouts and independent/duplicated reading of system info because it's a expensive call.

PS: I haven't changed the settings page. There is shown a delay of 30sec in the description for "Broadcast system state".

### CODE REVIEW

**Comment by RonnyWinkler** [comment]
Hello Harrie,
perhaps I found a memory leak issue in Homey...
Reading the memory usage from Homey seems to raise the memory usage of Homey core. I created a ticket at AthomSupport.
I don't know if it's a memory leak or if I call it too often and the garbage collector can't clear it fast enough. But it results in a state where Homey core uses all memory and all apps are killed.

So please wait with  the merge until I get a response from Athom and there is a solution. 
In the meantime I could deactivate the memory depending code. This way you could merge the part with the cpu usage. Please let me know...
Bye
Ronny

**Comment by RonnyWinkler** [comment]
Hello Harrie,
I splittedt the system load and memory usage into 2 separate timeouts.
The memory variant is commented/deactivated because of the memory issued reported to Athom. 
This way, the system load can be tested an published. 
The memory usage could be activated if Athom will provide a solution for the memory issue.
Bye
Ronny

**Comment by harriedegroot** [comment]
Thanks Ronny! I'll review (and merge) asap.

**Comment by RonnyWinkler** [comment]
Here is an example for a visual presentation of the system load in HomeAssistant...
grafik

**Comment by RonnyWinkler** [comment]
Hello Harrie,
are you still planning to merge this request?
I don't get updates with my current developer version so I just want to know what you are planning for the next time. Thanks.
Ronny

**Comment by RonnyWinkler** [comment]
I came across that this addition is causing too much memory issues. So it's easier to use the default system info and extract it in HA from the JSON. Free memory and CPU is most important and that is delivered.

**Pull request closed without merging**
